### Import liberaries

In [4]:
!pip install pandas numpy matplotlib seaborn

Collecting pandas
  Downloading pandas-3.0.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 475.9 kB/s eta 0:00:00a 0:00:01
Collecting numpy
  Downloading numpy-2.4.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting matplotlib
  Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.8/52.8 kB 2.0 MB/s eta 0:00:00
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/java/epsilon/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.62.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.5/117.5 kB 1.8 MB/s eta 0:00:00a 0:00:01
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Requirement already satisfied: packaging>=20.0 in /home/java/epsilon/.venv/lib/python3.12/site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.1.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in /home/java/epsilon/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 2.8 MB/s eta 0:00:0000:0100:01
Downloading numpy-2.4.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 3.7 MB/s eta 0:00:0000:0100:01
Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 3.7 MB/s eta 0:00:0000:0100:01
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (362 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 3.6 MB/s eta 0:00:0000:0100:01
Downloading kiwisolver-1.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 3.5 MB/s eta 0:00:0000:0100:01
Downloading pillow-12.1.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 3.2 MB/s eta 0:00:0000:0100:01
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.8/122.8 kB 4.8 MB/s eta 0:00:00
Installing collected packages: pyparsing, pillow, numpy, kiwisolver, fonttools, cycler, pandas, contourpy, matplotlib, seaborn
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.62.1 kiwisolver-1.5.0 matplotlib-3.10.8 numpy-2.4.3 pandas-3.0.1 pillow-12.1.1 pyparsing-3.3.2 seaborn-0.13.2

In [13]:
import pandas as pd
import numpy as np

from datetime import datetime

# set pandas to display all columns
pd.set_option('display.max_columns',None)

### Load data

In [14]:
listing_df = pd.read_csv('../data/raw/Listings.csv' ,
                            encoding = "ISO-8859-1" ,           # this will handle the special characters
                            low_memory=False                    # this will prevent dtype warning due to mixed types in columns
                        ) 
listing_df.head()

,listing_id,name,host_id,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood,district,city,latitude,longitude,property_type,room_type,accommodates,bedrooms,amenities,price,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable
0,281420,"Beautiful Flat in le Village Montmartre, Paris",1466919,2011-12-03,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,t,f,Buttes-Montmartre,NaN,Paris,48.88668,2.33343,Entire apartment,Entire place,2,1.0,"[""Heating"", ""Kitchen"", ""Washer"", ""Wifi"", ""Long...",53,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
1,3705183,39 mÃÂ² Paris (Sacre CÃ âur),10328771,2013-11-29,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,t,t,Buttes-Montmartre,NaN,Paris,48.88617,2.34515,Entire apartment,Entire place,2,1.0,"[""Shampoo"", ""Heating"", ""Kitchen"", ""Essentials""...",120,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
2,4082273,"Lovely apartment with Terrace, 60m2",19252768,2014-07-31,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,t,f,Elysee,NaN,Paris,48.88112,2.31712,Entire apartment,Entire place,2,1.0,"[""Heating"", ""TV"", ""Kitchen"", ""Washer"", ""Wifi"",...",89,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
3,4797344,Cosy studio (close to Eiffel tower),10668311,2013-12-17,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,t,t,Vaugirard,NaN,Paris,48.84571,2.30584,Entire apartment,Entire place,2,1.0,"[""Heating"", ""TV"", ""Kitchen"", ""Wifi"", ""Long ter...",58,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
4,4823489,Close to Eiffel Tower - Beautiful flat : 2 rooms,24837558,2014-12-14,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,t,f,Passy,NaN,Paris,48.85500,2.26979,Entire apartment,Entire place,2,1.0,"[""Heating"", ""TV"", ""Kitchen"", ""Essentials"", ""Ha...",60,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f

### Data cleaning

#### first check the city data and filter it

In [15]:
listing_df['city'].unique()            # then we will filter this to work with paris data only

<StringArray>
[         'Paris',       'New York',        'Bangkok', 'Rio de Janeiro',
         'Sydney',       'Istanbul',           'Rome',      'Hong Kong',
    'Mexico City',      'Cape Town']
Length: 10, dtype: str

In [16]:
def data_filtering_pipeline(listing_df):
    paris_df=listing_df.copy() 
    # work with paris data only 
    paris_df = paris_df[paris_df['city'] == 'Paris']
    return paris_df

paris_df = data_filtering_pipeline(listing_df)
paris_df['city'].unique()

<StringArray>
['Paris']
Length: 1, dtype: str

#### Explore data

In [17]:
paris_df.info()           # to check data type per column

<class 'pandas.DataFrame'>
Index: 64690 entries, 0 to 279711
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   listing_id                   64690 non-null  int64
 1   name                         64627 non-null  str
 2   host_id                      64690 non-null  int64
 3   host_since                   64657 non-null  str
 4   host_location                64522 non-null  str
 5   host_response_time           23346 non-null  str
 6   host_response_rate           23346 non-null  float64
 7   host_acceptance_rate         31919 non-null  float64
 8   host_is_superhost            64657 non-null  str
 9   host_total_listings_count    64657 non-null  float64
 10  host_has_profile_pic         64657 non-null  str
 11  host_identity_verified       64657 non-null  str
 12  neighbourhood                64690 non-null  str
 13  district                     0 non-null      str
 14  city                         64690 non-null  str
 15  latitude                     64690 non-null  float64
 16  longitude                    64690 non-null  float64
 17  property_type                64690 non-null  str
 18  room_type                    64690 non-null  str
 19  accommodates                 64690 non-null  int64
 20  bedrooms                     51286 non-null  float64
 21  amenities                    64690 non-null  str
 22  price                        64690 non-null  int64
 23  minimum_nights               64690 non-null  int64
 24  maximum_nights               64690 non-null  int64
 25  review_scores_rating         48036 non-null  float64
 26  review_scores_accuracy       47989 non-null  float64
 27  review_scores_cleanliness    47998 non-null  float64
 28  review_scores_checkin        47972 non-null  float64
 29  review_scores_communication  47991 non-null  float64
 30  review_scores_location       47971 non-null  float64
 31  review_scores_value          47972 non-null  float64
 32  instant_bookable             64690 non-null  str
dtypes: float64(13), int64(6), str(14)
memory usage: 16.8 MB

In [18]:
paris_df.describe()

,listing_id,host_id,host_response_rate,host_acceptance_rate,host_total_listings_count,latitude,longitude,accommodates,bedrooms,price,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
count,6.469000e+04,6.469000e+04,23346.000000,31919.000000,64657.000000,64690.000000,64690.000000,64690.000000,51286.000000,64690.000000,64690.000000,6.469000e+04,48036.000000,47989.000000,47998.000000,47972.000000,47991.000000,47971.000000,47972.000000
mean,2.423686e+07,8.796396e+07,0.859150,0.806684,11.739348,48.864199,2.345289,3.037997,1.369224,113.096445,5.741768,8.508504e+02,93.063931,9.595157,9.206446,9.686984,9.713071,9.685352,9.276703
std,1.432657e+07,1.048625e+08,0.280421,0.302462,71.333488,0.018327,0.033275,1.588766,0.952845,214.433668,44.877425,3.932168e+04,8.944810,0.847168,1.107371,0.775500,0.767611,0.702251,0.943098
min,2.577000e+03,2.626000e+03,0.000000,0.000000,0.000000,48.813170,2.228680,0.000000,1.000000,0.000000,1.000000,1.000000e+00,20.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
25%,1.180961e+07,1.274923e+07,0.890000,0.750000,1.000000,48.850870,2.324310,2.000000,1.000000,59.000000,1.000000,3.000000e+01,90.000000,9.000000,9.000000,10.000000,10.000000,10.000000,9.000000
50%,2.394850e+07,3.737947e+07,1.000000,0.970000,1.000000,48.865470,2.348180,2.000000,1.000000,80.000000,2.000000,1.125000e+03,95.000000,10.000000,9.000000,10.000000,10.000000,10.000000,9.000000
75%,3.720798e+07,1.316600e+08,1.000000,1.000000,2.000000,48.879100,2.370460,4.000000,2.000000,120.000000,4.000000,1.125000e+03,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
max,4.809185e+07,3.876640e+08,1.000000,1.000000,1105.000000,48.904910,2.467050,16.000000,50.000000,12000.000000,9999.000000,1.000000e+07,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [19]:
paris_df.isnull().sum().sort_values(ascending=False)

district                       64690
host_response_time             41344
host_response_rate             41344
host_acceptance_rate           32771
review_scores_location         16719
review_scores_value            16718
review_scores_checkin          16718
review_scores_accuracy         16701
review_scores_communication    16699
review_scores_cleanliness      16692
review_scores_rating           16654
bedrooms                       13404
host_location                    168
name                              63
host_total_listings_count         33
host_is_superhost                 33
host_since                        33
host_identity_verified            33
host_has_profile_pic              33
listing_id                         0
longitude                          0
host_id                            0
latitude                           0
city                               0
neighbourhood                      0
maximum_nights                     0
minimum_nights                     0
price                              0
amenities                          0
accommodates                       0
room_type                          0
property_type                      0
instant_bookable                   0
dtype: int64

#### change data types if needed

In [20]:
def convert_string_to_boolean(value):
    val=str(value).lower()
    if val == 't':
        return True
    else : 
        return False

In [21]:
bool_columns=['host_is_superhost','host_has_profile_pic','host_identity_verified' , 'instant_bookable']
for col in bool_columns:
    paris_df[col]=paris_df[col].apply(convert_string_to_boolean)

paris_df[bool_columns].dtypes

host_is_superhost         bool
host_has_profile_pic      bool
host_identity_verified    bool
instant_bookable          bool
dtype: object

In [22]:
paris_df['host_since'] = pd.to_datetime(paris_df['host_since'])
paris_df['host_since'].dtype

dtype('<M8[us]')

In [23]:
paris_df['bedrooms'] = paris_df['bedrooms'].astype('Int64')
paris_df['bedrooms'].dtype

Int64Dtype()

#### fill null values

In [ ]:
paris_df.drop(columns=['district'], inplace=True)